[project]
name = 'Blockchain-Based-Electronics-Component-Lifecycle-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.component-tracking]
path = 'contracts/component-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.end-of-life-management]
path = 'contracts/end-of-life-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
